### ISSUE TITLE
Changing "People" route to "/people"

### ISSUE THREAD

**Issue by Daddy** [KinkyCommunity/Issues#2]
## Description
Currently, all of the menu items / core features of Kinky Community relate to their associated route.
* Interests -> /interests
* Organizations -> /organizations
* Venues -> /venues
* Events -> /events

However the routing for People is as follows:
* People -> /users

This brings an small level of inconsistency.

**Comment by KinkyCommunityTeam** [comment]
I doubt most users care of pay attention to the URLs/routes of pages.

But this is fixed now ;-)
