### ISSUE TITLE
Toggling "Anyone can Message" New Conversation on own Profile

### ISSUE THREAD

**Issue by Daddy** [KinkyCommunity/Issues#4]
## Description
By toggling the option "anyone can message you without liking you first", it unintentionally displays a "New Conversation" button on your own profile, allowing you to message yourself.

### Additional Notes
Should messaging yourself be allowed? It currently functions without restrictions.

**Comment by KinkyCommunityTeam** [comment]
No, you shouldn't be able to message yourself.

**Comment by KinkyCommunityTeam** [comment]
This is fixed now.
